// Program to understand the default throw and default catch
import java.util.*;
public class Exception_handling1 {
    public static void main(String[] args) {
        int x,y;
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the value of x and y:");
        x = sc.nextInt();
        y = sc.nextInt();
        System.out.println("The division of x and y = "+x/y);
        System.out.println("Program continued after Exception.");
        
                

    }
}
